### ISSUE TITLE
Code Release Roadmap

### ISSUE THREAD

**Issue by KDharmarajanDev** [BerkeleyAutomation/mirage#6]
There are additional features and documentation that we are planning on releasing publicly, please see the roadmap below.

- [ ] Increase coverage on Documentation [5/12]
- [x] Release model checkpoints used for evaluation [3/22]
- [ ] Integrate latest ORBIT version [5/24]
- [ ] Rework process communication backend to avoid sockets [5/25]
